pipeline {
   agent any
    environment{
  
       DOCKER_TAG= getDockerTag()
       registryCredential='DockerHub_ID'
 
   }
   stages {
      
       stage('checkout') {
           steps {
               checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/mayssa-bm/todo-app']]])
           }
       }
      
       stage('Build Docker image'){
           steps{
               script{
                   sh "docker build . -t maissa47/todo-app:${DOCKER_TAG}"
               }
           
              
           }
       }
      
         stage('Push Image') {
           steps{   
               script{
                   docker.withRegistry( '', registryCredential ) {
                   sh "docker push maissa47/todo-app:${DOCKER_TAG}"
                   }
               }
               
           }
       }
      
        stage('deploy with ansible') {
           steps {
               script{
               sh '''
                whoami
                sudo -u maissa ansible-playbook -e "image=maissa47/todo-app:${DOCKER_TAG}" /home/maissa/Desktop/k8s-ansible-role-config2.yml
               '''
               }
           }
       }
      
   }
}
 
def getDockerTag(){
   def tag = sh script: 'git rev-parse HEAD', returnStdout: true
   return tag
}
